// @ts-check
/**
 * 把项目规范里能静态检查的条款变成测试。
 *
 * 这些是回归守卫：以后谁把 `Date.now()` 写回领域层、或在代码注释里塞 emoji，
 * 测试会当场拦下来，而不是等到线上才发现。
 */
import assert from 'node:assert/strict'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { test } from 'node:test'

const packageRoot = new URL('..', import.meta.url)
const coreRoot = new URL('packages/pet-core/src/', packageRoot)

/** Every .js file below `dirUrl` (missing directories are simply empty). */
function jsFiles(dirUrl) {
  if (!existsSync(dirUrl)) return []
  const out = []
  for (const entry of readdirSync(dirUrl, { withFileTypes: true })) {
    const child = new URL(`${entry.name}${entry.isDirectory() ? '/' : ''}`, dirUrl)
    if (entry.isDirectory()) out.push(...jsFiles(child))
    else if (entry.name.endsWith('.js')) out.push(child)
  }
  return out
}

const read = url => readFileSync(url, 'utf8')
const shortName = url => url.pathname.split('/').slice(-2).join('/')

test('the domain layer never reads the system clock', () => {
  // The domain lives in packages/pet-core: core.js is its barrel, core/ the modules.
  const files = [new URL('core.js', coreRoot), ...jsFiles(new URL('core/', coreRoot))]
  const offenders = files.filter(url => /Date\.now\(\)/.test(read(url))).map(shortName)
  assert.deepEqual(
    offenders,
    [],
    'pass nowMs in as a parameter instead of reading the clock inside core (CONVENTIONS §分层)',
  )
})

test('code identifiers, comments and logs carry no emoji', () => {
  // Game data (data/) and user-facing copy (CHANGELOG, panel strings) are exempt
  // by the project conventions; this checks the code layers.
  const emoji = /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{FE0F}]/u
  const files = [
    new URL('core.js', packageRoot),
    new URL('core.js', coreRoot),
    new URL('index.js', packageRoot),
    new URL('store.js', packageRoot),
    new URL('render.js', packageRoot),
    ...jsFiles(new URL('core/', coreRoot)),
    ...jsFiles(new URL('store/', packageRoot)),
    ...jsFiles(new URL('src/client/', packageRoot)),
    ...jsFiles(new URL('apps/desktop/lib/', packageRoot)),
    new URL('apps/desktop/main.js', packageRoot),
    // extensions/ 不查：注释里用 ★ 表示星级（盲盒 3★～6★），是领域写法；改它还得重新发扩展
  ]
  const offenders = []
  for (const url of files) {
    read(url).split('\n').forEach((line, index) => {
      const stripped = line.trim()
      const isComment = stripped.startsWith('//') || stripped.startsWith('/*') || stripped.startsWith('*')
      if (isComment && emoji.test(line)) offenders.push(`${shortName(url)}:${index + 1}`)
    })
  }
  assert.deepEqual(offenders, [], 'comments explain why in words; emoji belong in the game data and UI copy')
})

test('源码最多 400 行，单文件下载的扩展 server.js 最多 600 行', () => {
  // client.js is generated by scripts/build-client.mjs, so it is exempt.
  const files = [
    new URL('index.js', packageRoot),
    new URL('snapshot.js', packageRoot),
    new URL('commands.js', packageRoot),
    new URL('routes.js', packageRoot),
    new URL('store.js', packageRoot),
    new URL('render.js', packageRoot),
    ...jsFiles(new URL('data/', coreRoot)),
    ...jsFiles(new URL('core/', coreRoot)),
    ...jsFiles(new URL('store/', packageRoot)),
    ...jsFiles(new URL('src/client/', packageRoot)),
    // 桌面外壳的模块和在线扩展同样受限；apps/desktop/main.js 暂时豁免（见 CONVENTIONS「豁免」）
    ...jsFiles(new URL('apps/desktop/lib/', packageRoot)),
    ...jsFiles(new URL('extensions/', packageRoot)),
  ]
  const lineCount = url => read(url).replace(/\n$/, '').split('\n').length
  const limit = url => /\/extensions\/[^/]+\/server\.js$/.test(url.pathname) ? 600 : 400
  const offenders = files.filter(url => lineCount(url) > limit(url)).map(url => `${shortName(url)}:${lineCount(url)}>${limit(url)}`)
  assert.deepEqual(offenders, [], 'split the file instead of growing past 400 lines (CONVENTIONS §分层)')
})

test('外壳模块和在线扩展的规则文件开头都有 // @ts-check', () => {
  const files = [...jsFiles(new URL('apps/desktop/lib/', packageRoot)), new URL('apps/desktop/main.js', packageRoot),
    ...jsFiles(new URL('extensions/', packageRoot)).filter(url => url.pathname.endsWith('server.js'))]
  assert.deepEqual(files.filter(url => !read(url).startsWith('// @ts-check')).map(shortName), [])
})

test('package.json ships every module the runtime imports', () => {
  // Splitting files is only safe if the published tarball carries them: the
  // `files` allow-list decides that, and a missing directory breaks the plugin
  // for anyone who installs it from npm (the local link hides the mistake).
  const manifest = JSON.parse(read(new URL('package.json', packageRoot)))
  const listed = new Set(manifest.files)
  const required = [
    'index.js', 'snapshot.js', 'commands.js', 'routes.js', 'core.js', 'data.js',
    'store.js', 'render.js', 'client.js', 'packages/pet-core', 'store', 'src', 'scripts',
    'THIRD-PARTY.md', 'LICENSE',
  ]
  const missing = required.filter(entry => !listed.has(entry))
  assert.deepEqual(missing, [], 'add these to package.json files:')
  const absent = [...listed].filter(entry => !existsSync(new URL(entry, packageRoot)))
  assert.deepEqual(absent, [], 'files lists something that is not in the package:')
})

test('the typecheck command the conventions promise actually exists', () => {
  // docs/CONVENTIONS.md tells contributors to run `npm run typecheck`; it was
  // documented for a while before the script existed.
  const manifest = JSON.parse(read(new URL('package.json', packageRoot)))
  assert.equal(manifest.scripts.typecheck, 'node scripts/typecheck.mjs')
  assert.ok(existsSync(new URL('scripts/typecheck.mjs', packageRoot)), 'scripts/typecheck.mjs must exist')
})
