#!/usr/bin/env python3
"""Measure transparent feedback art for display framing.

Run with: uv run --with pillow python tools/measure-feedback-framing.py
The committed output is read at runtime; Pillow is never required by the game.
"""

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "assets" / "feedback"
OUTPUT = ROOT / "src" / "client" / "feedback-framing.js"
# The built-in piglet SVG occupies 239 of 256 pixels on its longest side.
TARGET = 239 / 256
ALPHA_THRESHOLD = 16


def framing(path):
    image = Image.open(path).convert("RGBA")
    alpha = image.getchannel("A")
    bounds = alpha.point(lambda value: 255 if value > ALPHA_THRESHOLD else 0).getbbox()
    if bounds is None:
        return None
    width, height = image.size
    left, top, right, bottom = bounds
    occupied = max((right - left) / width, (bottom - top) / height)
    zoom = max(1, TARGET / occupied)
    if zoom < 1.01:
        return None
    shift_x = (0.5 - (left + right) / (2 * width)) * zoom * 100
    shift_y = (0.5 - (top + bottom) / (2 * height)) * zoom * 100
    return round(zoom, 4), round(shift_x, 2), round(shift_y, 2)


entries = []
for path in sorted(ART.glob("*.png")):
    frame = framing(path)
    if frame is not None:
        entries.append((path.stem, frame))

lines = [
    "// Generated by tools/measure-feedback-framing.py; do not edit by hand.",
    "// Values: [zoom, horizontal shift %, vertical shift %] in the original square frame.",
    "export const FEEDBACK_FRAMING = Object.freeze({",
]
for name, (zoom, x, y) in entries:
    lines.append(f"  '{name}': [{zoom}, {x}, {y}],")
lines.append("})")
OUTPUT.write_text("\n".join(lines) + "\n")
print(f"Wrote {len(entries)} frames to {OUTPUT}")
