#!/usr/bin/env python3
"""Calibrate all built-in artwork to the existing piglet's visible height.

uv run --with pillow --with cairosvg python tools/measure-feedback-framing.py
Only metadata is written; approved images are never changed.
"""
from io import BytesIO
from pathlib import Path
import cairosvg
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/client/feedback-framing.js"
THRESHOLD = 16


def load(path):
    if path.suffix == ".svg":
        return Image.open(BytesIO(cairosvg.svg2png(url=str(path), output_width=256, output_height=256))).convert("RGBA")
    return Image.open(path).convert("RGBA")


def bounds(image):
    return image.getchannel("A").point(lambda a: 255 if a > THRESHOLD else 0).getbbox()


reference = load(ROOT / "assets/piglet.svg")
_, top, _, bottom = bounds(reference)
TARGET = (bottom - top) / reference.height


def framing(path):
    image = load(path)
    box_width = 1.2 if path.stem.endswith("-sleep") else 1
    left, top, right, bottom = bounds(image)
    fit = min(box_width / image.width, 1 / image.height)
    zoom = TARGET / ((bottom - top) * fit)
    x = (image.width / 2 - (left + right) / 2) * fit * zoom / box_width * 100
    y = (image.height / 2 - (top + bottom) / 2) * fit * zoom * 100
    return round(zoom, 4), round(x, 2), round(y, 2)


feedback = sorted((ROOT / "assets/feedback").glob("*.png"))
builtin = sorted(p for p in (ROOT / "assets").iterdir()
                 if p.suffix in (".svg", ".png") and p.stem.startswith(("pig", "skin-", "career-")))
lines = ["// Generated by tools/measure-feedback-framing.py; do not edit by hand.",
         "// Values: [zoom, horizontal shift %, vertical shift %]; alpha bounds share one visible height.",
         f"export const FRAME_HEIGHT = {TARGET}"]
for name, paths, key in [("FEEDBACK_FRAMING", feedback, lambda p: p.stem),
                         ("BUILTIN_FRAMING", builtin, lambda p: p.name)]:
    lines.append(f"export const {name} = Object.freeze({{")
    for path in paths:
        zoom, x, y = framing(path)
        lines.append(f"  '{key(path)}': [{zoom}, {x}, {y}],")
    lines.append("})")
OUTPUT.write_text("\n".join(lines) + "\n")
print(f"Wrote {len(feedback)} feedback and {len(builtin)} built-in frames; reference height {TARGET}")
