#!/usr/bin/env python3
"""Calibrate classified PNGs without changing their pixels.

uv run --with pillow python tools/measure-feedback-framing.py
"""
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'src/client/feedback-framing.js'
# Preserve the established standard visible height and imported-skin scaling.
TARGET = 0.84375
THRESHOLD = 16


def framing(entry):
    image = Image.open(ROOT / 'assets' / entry['path']).convert('RGBA')
    box_width = 1.2 if entry['action'] == 'sleep' else 1
    left, top, right, bottom = image.getchannel('A').point(lambda a: 255 if a > THRESHOLD else 0).getbbox()
    fit = min(box_width / image.width, 1 / image.height)
    zoom = TARGET / ((bottom - top) * fit)
    x = (image.width / 2 - (left + right) / 2) * fit * zoom / box_width * 100
    y = (image.height / 2 - (top + bottom) / 2) * fit * zoom * 100
    return round(zoom, 4), round(x, 2), round(y, 2)


entries = json.loads((ROOT / 'assets/pigs/manifest.json').read_text())
feedback = [e for e in entries if e['action'] == 'scene']
builtin = [e for e in entries if e['action'] not in ['scene', 'badge']]
lines = ['// Generated by tools/measure-feedback-framing.py; do not edit by hand.',
         '// Values: [zoom, horizontal shift %, vertical shift %]; alpha bounds share one visible height.',
         f'export const FRAME_HEIGHT = {TARGET}']
for name, rows in [('FEEDBACK_FRAMING', feedback), ('BUILTIN_FRAMING', builtin)]:
    lines.append(f'export const {name} = Object.freeze({{')
    for entry in sorted(rows, key=lambda e: e['key']):
        key = entry['actor'] if name == 'FEEDBACK_FRAMING' else entry['path']
        zoom, x, y = framing(entry)
        lines.append(f"  '{key}': [{zoom}, {x}, {y}],")
    lines.append('})')
lines.append('export const ART_BOUNDS = Object.freeze({')
for entry in entries:
    bounds = [round(value / 256, 6) for value in entry['bounds']]
    lines.append(f"  '{entry['path']}': {json.dumps(bounds)},")
lines.append('})')
aspect = max((e['bounds'][2] - e['bounds'][0]) / (e['bounds'][3] - e['bounds'][1]) for e in entries)
lines.append(f'export const MAX_ART_ASPECT = {round(aspect, 6)}')
OUTPUT.write_text('\n'.join(lines) + '\n')
print(f'Wrote {len(feedback)} feedback and {len(builtin)} built-in frames')
