#!/usr/bin/env python3
"""Export approved originals as classified transparent game PNGs.

uv run --with pillow python tools/prepare-pig-art.py SELECTION_JSON
The selection and original images stay outside the repository.
"""
import argparse
import hashlib
import json
import shutil
from pathlib import Path

from PIL import Image, ImageChops

ROOT = Path(__file__).resolve().parents[1]
SIDE = 256
PADDING = 16
FORMS = {"pig-round", "pig-fat", "pig-king", "pig-devil"}


def location(item):
    actor, action = item["actor"], item["action"]
    if action == "scene":
        return "feedback/" + actor, f"pigs/feedback/{actor}.png"
    if action == "badge":
        return actor, f"pigs/badges/{actor}.png"
    group = "base" if actor in {"piglet", "elder"} else "forms" if actor in FORMS else "skins"
    key = actor if action == "idle" else actor + "-" + action
    return key, f"pigs/{group}/{actor}/{action}.png"


def prepare(source, output):
    with Image.open(source) as original:
        image = original.convert("RGBA")
        alpha = image.getchannel("A")
        if alpha.getextrema()[0] != 0:
            raise ValueError(f"{source}: original must already have a transparent background")
        # Remove negligible generator noise, retain antialiasing and translucent
        # scene elements. Near-opaque white costumes stay fully opaque.
        alpha = alpha.point(lambda a: 0 if a <= 8 else 255 if a >= 248 else round((a - 8) * 255 / 240))
        visible = alpha.point(lambda a: 255 if a > 16 else 0).getbbox()
        if visible is None:
            raise ValueError(f"{source}: empty artwork")
        mask = alpha.point(lambda a: 255 if a else 0)
        red, green, blue, _ = image.split()
        image = Image.merge("RGBA", (ImageChops.multiply(red, mask), ImageChops.multiply(green, mask),
                                     ImageChops.multiply(blue, mask), alpha)).crop(visible)
        fit = min((SIDE - 2 * PADDING) / image.width, (SIDE - 2 * PADDING) / image.height)
        size = (max(1, round(image.width * fit)), max(1, round(image.height * fit)))
        # Premultiplied resize prevents RGB hidden in transparent pixels from
        # producing dark or white fringes around the black outlines.
        image = image.convert("RGBa").resize(size, Image.Resampling.LANCZOS).convert("RGBA")
        canvas = Image.new("RGBA", (SIDE, SIDE))
        canvas.alpha_composite(image, ((SIDE - image.width) // 2, (SIDE - image.height) // 2))
        # PNG's palette carries per-color alpha (tRNS), including transparent
        # background and antialiased edges; opaque white details stay opaque.
        canvas = canvas.quantize(colors=256, method=Image.Quantize.FASTOCTREE,
                                 dither=Image.Dither.NONE)
        output.parent.mkdir(parents=True, exist_ok=True)
        canvas.save(output, optimize=True, compress_level=9)
        bounds = canvas.convert("RGBA").getchannel("A").point(lambda a: 255 if a > 16 else 0).getbbox()
        return list(original.size), list(visible), list(bounds), output.stat().st_size


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("selection", type=Path)
    args = parser.parse_args()
    selected = json.loads(args.selection.read_text())
    entries, paths = [], {}
    prompt_dir = ROOT / "docs/art-prompts/outlined-pigs"
    prompt_dir.mkdir(parents=True, exist_ok=True)
    for item in selected:
        key, path = location(item)
        if key in paths:
            raise ValueError(f"Duplicate artwork key: {key}")
        source = Path(item["image"])
        output = ROOT / "assets" / path
        dimensions, bounds, output_bounds, size = prepare(source, output)
        prompt = source.parent.parent / "prompts" / (item["name"] + ".txt")
        if not prompt.is_file():
            raise ValueError(f"Missing exact prompt: {prompt}")
        shutil.copy2(prompt, prompt_dir / prompt.name)
        paths[key] = path
        entries.append({"key": key, "path": path, "actor": item["actor"], "action": item["action"],
                        "version": item["name"], "tool": "image_gen", "prompt": "docs/art-prompts/outlined-pigs/" + prompt.name,
                        "sourceSha256": hashlib.sha256(source.read_bytes()).hexdigest(),
                        "sourceDimensions": dimensions, "sourceBounds": bounds, "bounds": output_bounds,
                        "sha256": hashlib.sha256(output.read_bytes()).hexdigest(), "bytes": size})
    (ROOT / "assets/pigs/manifest.json").write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n")
    lines = ["// @ts-check", "// Generated by tools/prepare-pig-art.py from reviewed originals.",
             "/** @type {Readonly<Record<string, string>>} */", "export const PIG_ART_ASSETS = Object.freeze({"]
    lines += [f"  {json.dumps(key)}: {json.dumps(path)}," for key, path in sorted(paths.items())]
    lines += ["})", ""]
    (ROOT / "packages/pet-core/src/data/art-assets.js").write_text("\n".join(lines))
    print(f"Exported {len(entries)} PNGs, {sum(e['bytes'] for e in entries):,} bytes")


if __name__ == "__main__":
    main()
